/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Logica.cls_vehiculo;
import java.util.LinkedList;
import javax.swing.JOptionPane;

/**
 *
 * @author sala104
 */
public class frm_registro extends javax.swing.JFrame {

    LinkedList<cls_vehiculo> vehiculos = new LinkedList<>();
    
    public frm_registro() {
        initComponents();
        setLocationRelativeTo(null);
        setSize(700, 560);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        txt_placa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_descripcion = new javax.swing.JTextArea();
        txt_nombre_conductor = new javax.swing.JTextField();
        txt_ruta = new javax.swing.JTextField();
        txt_marca = new javax.swing.JTextField();
        txt_modelo = new javax.swing.JTextField();
        btn_registrar = new javax.swing.JButton();
        btn_nuevo = new javax.swing.JButton();
        btn_consultar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(7, 65, 115));
        jPanel1.setForeground(new java.awt.Color(197, 255, 149));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Titulo.setForeground(new java.awt.Color(197, 255, 149));
        Titulo.setText("Registros de Transporte LTDA");
        jPanel1.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        txt_placa.setBackground(new java.awt.Color(7, 65, 115));
        txt_placa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_placa.setForeground(new java.awt.Color(255, 255, 255));
        txt_placa.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_placa.setToolTipText("Placa");
        txt_placa.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(93, 235, 215)));
        txt_placa.setMargin(new java.awt.Insets(3, 3, 3, 3));
        txt_placa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_placaActionPerformed(evt);
            }
        });
        jPanel1.add(txt_placa, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 310, 30));

        txt_descripcion.setColumns(20);
        txt_descripcion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_descripcion.setRows(5);
        txt_descripcion.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(93, 235, 215)));
        jScrollPane1.setViewportView(txt_descripcion);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 310, 120));

        txt_nombre_conductor.setBackground(new java.awt.Color(7, 65, 115));
        txt_nombre_conductor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_nombre_conductor.setForeground(new java.awt.Color(255, 255, 255));
        txt_nombre_conductor.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(93, 235, 215)));
        jPanel1.add(txt_nombre_conductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 310, 30));

        txt_ruta.setBackground(new java.awt.Color(7, 65, 115));
        txt_ruta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_ruta.setForeground(new java.awt.Color(255, 255, 255));
        txt_ruta.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(93, 235, 215)));
        txt_ruta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_rutaActionPerformed(evt);
            }
        });
        jPanel1.add(txt_ruta, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 310, 30));

        txt_marca.setBackground(new java.awt.Color(7, 65, 115));
        txt_marca.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_marca.setForeground(new java.awt.Color(255, 255, 255));
        txt_marca.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(93, 235, 215)));
        jPanel1.add(txt_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 310, 30));

        txt_modelo.setBackground(new java.awt.Color(7, 65, 115));
        txt_modelo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_modelo.setForeground(new java.awt.Color(255, 255, 255));
        txt_modelo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(93, 235, 215)));
        jPanel1.add(txt_modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, 310, 30));

        btn_registrar.setText("Registrar");
        btn_registrar.setFocusPainted(false);
        btn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 480, -1, -1));

        btn_nuevo.setText("Nuevo");
        btn_nuevo.setFocusPainted(false);
        btn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btn_nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 480, -1, -1));

        btn_consultar.setText("Consultar");
        btn_consultar.setFocusPainted(false);
        btn_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_consultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 480, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(197, 255, 149));
        jLabel2.setText("Descripcion:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(197, 255, 149));
        jLabel3.setText("Nombre conductor:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(197, 255, 149));
        jLabel4.setText("Ruta:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(197, 255, 149));
        jLabel5.setText("Marca:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(197, 255, 149));
        jLabel6.setText("Modelo:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(197, 255, 149));
        jLabel7.setText("Placa:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_placaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_placaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_placaActionPerformed

    private void txt_rutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_rutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_rutaActionPerformed

    public void fnt_limpiar(){
    txt_placa.setText("");
    txt_descripcion.setText("");
    txt_nombre_conductor.setText("");
    txt_ruta.setText("");
    txt_marca.setText("");
    txt_modelo.setText("");
    txt_placa.requestFocus();
    
    
    }
    private void btn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoActionPerformed
        fnt_limpiar();
    }//GEN-LAST:event_btn_nuevoActionPerformed
    
    public void fnt_registrar(){
    
    int validacionInt = 1;
    
    cls_vehiculo v1 = new cls_vehiculo(txt_placa.getText(), txt_descripcion.getText(), 
                                       txt_nombre_conductor.getText(), txt_ruta.getText(), txt_marca.getText(), 
                                       txt_modelo.getText());
        
    if(txt_placa.getText().isEmpty() || txt_descripcion.getText().isEmpty() || 
       txt_nombre_conductor.getText().isEmpty() || txt_ruta.getText().isEmpty()|| 
       txt_marca.getText().isEmpty() || txt_modelo.getText().isEmpty()){
    
        JOptionPane.showMessageDialog(null, "!!!!Error, campos sin llenar!!!!!", "Error", JOptionPane.ERROR_MESSAGE);
        validacionInt =0;
    }
    
    for (cls_vehiculo vehiculo : vehiculos){
         
         if(vehiculo.getPlacaStr().equals(v1.getPlacaStr())){
         
         JOptionPane.showMessageDialog(null, "!!!!Error, el vehiculo ya existe en la base de datos!!!!!", "Error", JOptionPane.ERROR_MESSAGE);
            validacionInt = 0;
         }
    
    }
    
    if(validacionInt == 1){
      
        vehiculos.add(v1);
        JOptionPane.showMessageDialog(null, "Vehiculo registrado con exito!!", "Registro", JOptionPane.INFORMATION_MESSAGE);
     }
    
    }
    
    
    private void btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarActionPerformed
        fnt_registrar();
    }//GEN-LAST:event_btn_registrarActionPerformed

    public void fnt_consultar(){
    
        for (cls_vehiculo vehiculo : vehiculos) {
            if(vehiculo.getPlacaStr().equals(txt_placa.getText())){
                txt_descripcion.setText(vehiculo.getDescripcionStr());
                txt_nombre_conductor.setText(vehiculo.getNombre_conductorStr());
                txt_ruta.setText(vehiculo.getRutaStr());
                txt_marca.setText(vehiculo.getMarcaStr());
                txt_modelo.setText(vehiculo.getModeloStr());
            }else{
                
                JOptionPane.showMessageDialog(null, "!!!!Error,No se encontraron registros en la base de datos", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    
    }
    
    private void btn_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultarActionPerformed
        fnt_consultar();
    }//GEN-LAST:event_btn_consultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new frm_registro().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton btn_consultar;
    private javax.swing.JButton btn_nuevo;
    private javax.swing.JButton btn_registrar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txt_descripcion;
    private javax.swing.JTextField txt_marca;
    private javax.swing.JTextField txt_modelo;
    private javax.swing.JTextField txt_nombre_conductor;
    private javax.swing.JTextField txt_placa;
    private javax.swing.JTextField txt_ruta;
    // End of variables declaration//GEN-END:variables
}
